name: coderefinery
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.14
  - click=8.3.1
  - ipywidgets=8.1.8
  - jupyterlab=4.5.3
  - jupyterlab-git=0.51.4
  - matplotlib=3.10.8
  - myst-parser=5.0.0
  - nbdime=4.0.2
  - numpy=2.4.1
  - pandas=3.0.0
  - pytest=9.0.2
  - pytest-cov=7.0.0
  - seaborn=0.13.2
  - snakemake-minimal=9.14.8
  - sphinx=8.2.3
  - sphinx-autobuild=2025.8.25
  - sphinx_rtd_theme=3.1.0
  - sphinx-autodoc2=0.5.0
